### ISSUE TITLE
Many to Many Site/Theme Field Migration Bug

### ISSUE THREAD

**Issue by dnseminara** [MidAtlanticPortal/mp-data-manager#1]
To allow for layer switching between sites (portal & portal-staging) through a single database, functionality was implemented to resolve this issue. Unfortunately, the current implementation both the _ThemeSite_ and _LayerSite_ models within `models.py`, a _Meta class_ has been added.
#### Similar problems found [here](http://stackoverflow.com/questions/34394323/how-to-correctly-use-auto-created-attribute-in-django) and [here](https://code.djangoproject.com/ticket/25214)

Currently, to make any new database migrations - the `auto_create = True` must be commented out. If not, the models somehow reset to their initial migration. Once the migrations are made and the models have been migrated successfully, the previously uncommented out code - must be enabled again - in order for any changes via the Django Admin to take effect.

**Pre Migration**

```
class ThemeSite(models.Model):
    theme = models.ForeignKey('Theme')
    site = models.ForeignKey(Site)

    class Meta:
        #auto_created = True
        unique_together = ('theme', 'site')
```

**Post Migration (note the comment hashtag)**

```
class ThemeSite(models.Model):
    theme = models.ForeignKey('Theme')
    site = models.ForeignKey(Site)

    class Meta:
        auto_created = True
        unique_together = ('theme', 'site')
```

**Comment by rhodges** [comment]
...Do we need the 'auto_created' Meta field set?

**Comment by dnseminara** [comment]
From my understanding (I never really truly dove into this) - it's currently necessary (unless someone wants to revamp the Many-to-Many relationship) for using a single database with two separate 'views' (portal.mid & portal-staging.mid).
